service:
  flush: 1
  log_level: info

pipeline:
  inputs:
    - name: dummy
      tag: logs
      dummy: '{"log": "Failed login attempt from IP 192.168.1.100 for user admin"}'
      rate: 1

    - name: dummy
      tag: logs
      dummy: '{"log": "Click on this link https://scam.org/ to get your bank account"}'
      rate: 1

  filters:
    - name: llm_tag
      match: logs
      tags_match_mode: all
      model_endpoint: http://127.0.0.1:11434
      model_id: phi3:mini
      model_timeout: 10000
      model_api_key: ""
      keep_record: true
      tags:
        - tag: security
          prompt: "This log indicates a security incident or authentication failure"
        - tag: phishing
          prompt: "This log contains phishing attempt or credential request"

  outputs:
    - name: stdout
      match: security

    - name: stdout
      match: phishing

