---
name: Get image base names
# This reusable workflow extracts the canonical base names for UBI and Debian container images.
# It is intended to be lightweight and fast, so that it can be used in other workflows to get the base names without having to run the full get-metadata workflow.
# This is required to support some of the syntax limitations of GitHub Actions.
on:
  workflow_call:
    outputs:
      ubi-image-base:
        description: The canonical base name for UBI container images.
        value: ${{ jobs.get-image-bases.outputs.ubi-image-base }}
      debian-image-base:
        description: The canonical base name for Debian container images.
        value: ${{ jobs.get-image-bases.outputs.debian-image-base }}

env:
  # Set once from repo variable or override here for testing
  STEP_SECURITY_EGRESS_POLICY: ${{ vars.STEP_SECURITY_EGRESS_POLICY || 'audit' }}

permissions:
  contents: read

jobs:
  get-image-bases:
    name: Get image base names
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      ubi-image-base: ${{ steps.set-image-bases.outputs.ubi-image-base }}
      debian-image-base: ${{ steps.set-image-bases.outputs.debian-image-base }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: ${{ env.STEP_SECURITY_EGRESS_POLICY }}

      - name: Set image bases
        id: set-image-bases
        run: |
          UBI_IMAGE_BASE="ghcr.io/telemetryforge/agent/ubi"
          DEBIAN_IMAGE_BASE="ghcr.io/telemetryforge/agent/debian"
          echo "ubi-image-base=$UBI_IMAGE_BASE"
          echo "debian-image-base=$DEBIAN_IMAGE_BASE"
          echo "ubi-image-base=$UBI_IMAGE_BASE" >> $GITHUB_OUTPUT
          echo "debian-image-base=$DEBIAN_IMAGE_BASE" >> $GITHUB_OUTPUT
        shell: bash
