name: PR Package Build and Test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
env:
  # Set once from repo variable or override here for testing
  STEP_SECURITY_EGRESS_POLICY: ${{ vars.STEP_SECURITY_EGRESS_POLICY || 'audit' }}

# Default to least permissions and then we can add as needed for each job.
# This is a secure by default approach and also makes it easier to reason
# about permissions for each job since they are not implicit from the workflow
permissions: read-all

# Cancel any running jobs for PRs on a new commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  get-meta:
    name: Get meta information required for package builds
    uses: ./.github/workflows/call-get-metadata.yaml
    permissions:
      contents: read
    with:
      ref: ${{ github.ref }}
      get-version-from-tag: false
      use-full-linux-targets: true

  build-linux:
    # Only build Linux packages if we have a label set
    if: ${{ contains(github.event.pull_request.labels.*.name, 'build-packages') || contains(github.event.pull_request.labels.*.name, 'build-linux') }}
    uses: ./.github/workflows/call-build-linux-packages.yaml
    needs:
      - get-meta
    permissions:
      contents: read
      packages: read
    with:
      version: ${{ needs.get-meta.outputs.version }}
      ref: ${{ github.ref }}
      target-matrix: ${{ needs.get-meta.outputs.linux-targets }}
      nightly-build-info: ${{ needs.get-meta.outputs.date }}
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_PUBLIC_READ_TOKEN }}

  build-windows:
    # Only build Windows packages if we have a label set
    if: ${{ contains(github.event.pull_request.labels.*.name, 'build-packages') || contains(github.event.pull_request.labels.*.name, 'build-windows') }}
    uses: ./.github/workflows/call-build-windows-packages.yaml
    needs:
      - get-meta
    permissions:
      contents: read
    with:
      version: ${{ needs.get-meta.outputs.version }}
      ref: ${{ github.ref }}
      nightly-build-info: ${{ needs.get-meta.outputs.date }}

  build-macos:
    # Only build macOS packages with the label to reduce unnecessary CI costs
    if: ${{ contains(github.event.pull_request.labels.*.name, 'build-packages') || contains(github.event.pull_request.labels.*.name, 'build-macos') }}
    uses: ./.github/workflows/call-build-macos-packages.yaml
    needs:
      - get-meta
    permissions:
      contents: read
    with:
      version: ${{ needs.get-meta.outputs.version }}
      ref: ${{ github.ref }}
      nightly-build-info: ${{ needs.get-meta.outputs.date }}

  test-packages:
    name: Test packages
    needs:
      - get-meta
      - build-linux
    uses: ./.github/workflows/call-test-packages.yaml
    permissions:
      contents: read
      packages: read
    with:
      build-matrix: ${{ needs.get-meta.outputs.linux-targets }}
      version: ${{ needs.get-meta.outputs.version }}
      ref: ${{ github.ref }}
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_PUBLIC_READ_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  # Placeholder to make it simple to create a status check on this, do not change name.
  # Instead of modifying branch protection rules every time we add a new job, we just
  # add it as a dependency of this job.
  # This job must always run last so it depends on all other jobs that must complete.
  # Note that jobs that are conditionally run must be listed in allowed-skips.
  # If you add a new job that must complete then add it here.
  tests-complete:
    name: PR - Package tests complete
    if: always()
    needs:
      - build-linux
      - build-windows
      - build-macos
      - test-packages
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: ${{ env.STEP_SECURITY_EGRESS_POLICY }}

      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          allowed-skips: build-linux,build-windows,build-macos,test-packages
          jobs: ${{ toJSON(needs) }}

      - name: Package tests complete
        run: echo "Package tests complete"
        shell: bash
